create table if not exists accidenttype
(
    id   integer generated by default as identity
    primary key,
    name varchar(255)
    );


alter table accidenttype
    owner to postgres;

create table if not exists rule
(
    id   integer generated by default as identity
    primary key,
    name varchar(255)
    );


alter table rule
    owner to postgres;

create table if not exists accident
(
    id      integer generated by default as identity
    primary key,
    address varchar(255),
    name    varchar(255),
    text    varchar(255),
    type_id integer
    constraint fkewcfomkh7hbl50i7ue3b8i1dx
    references accidenttype
    );


alter table accident
    owner to postgres;

create table if not exists accident_rule
(
    accident_id integer not null
    constraint fkrqxx6nyiy2ms859svevmrhnb0
    references accident,
    rules_id    integer not null
    constraint fk3j3syu9yp1oj5i8rftnfm45nu
    references rule,
    primary key (accident_id, rules_id)
    );


alter table accident_rule
    owner to postgres;

